# AUTHOR: Rad Alzyoud
# Disclaimer: This SOFTWARE PRODUCT is provided by THE AUTHOR "as is" and "with all faults." THE AUTHOR makes no representations or warranties of any kind concerning the safety, suitability, lack of viruses, inaccuracies, typographical errors, or other harmful components of this SOFTWARE PRODUCT. There are inherent dangers in the use of any software, and you are solely responsible for determining whether this SOFTWARE PRODUCT is compatible with your environment and other software installed on your environment. You are also solely responsible for the protection of your environment and backup of your data, and THE AUTHOR will not be liable for any damages you may suffer in connection with using, modifying, or distributing this SOFTWARE PRODUCT.

- hosts: localhost
  vars:
   ansible_python_interpreter: "/usr/bin/python3.5"
  vars_prompt:
    name: passwd
    prompt: "{{ vcenter }} passwd for {{ login }} ? >>> "

  tasks:
  - name: Create a virtual machine "{{ vm_name }}"
    vmware_deploy_ovf:
      validate_certs: no
      hostname: "{{ vcenter }}"
      datacenter: "{{ datacenter }}"
      username: "{{ login }}"
      password: "{{ passwd }}"
      ovf: /repo/nsx-edge-2.5.0.0.0.13973346.ova
      name: "{{ vm_name }}"
      properties:
        #password: "VMware1!"
        "nsx_cli_passwd_0": "VMware1!"
        "nsx_cli_audit_passwd_0": "VMware1!!"
        "nsx_passwd_0": "VMware1!"
        "nsx_dns1_0": "192.168.110.10"
        "nsx_domain_0": "lab.rad"
        "nsx_gateway_0": "192.168.110.2"
        "nsx_hostname": "nsxt-edge-02"
        "nsx_ip_0": "192.168.110.62"
        "nsx_netmask_0": "255.255.255.0"
        "nsx_allowSSHRootLogin": "True"
        "nsx_isSSHEnabled": "True"
        "nsx_ntp_0": "0.us.pool.ntp.org"
      disk_provisioning: thin

      networks:
         "Network 0": "VSS-MGMT"

      cluster: "{{ cluster }}"
      datastore: "{{ datastore }}"
      power_on: no

